export default{
    '.alert-green' : {
        padding: "1em",
        borderRadius: "10px",
        backgroundColor: '#257035',
        border: "2px solid #2b8e41",
        opacity: "0.85",
    },
    '.alert-red' : {
        padding: "1em",
        borderRadius: "10px",
        backgroundColor: '#b22a2a',
        border: "2px solid #cd3535",
        opacity: "0.85",
    },
    '.alert-orange' : {
        padding: "1em",
        borderRadius: "10px",
        backgroundColor: '#ea580c',
        border: "2px solid #f97316",
        opacity: "0.85",
    },
    '.alert-yellow' : {
        padding: "1em",
        borderRadius: "10px",
        backgroundColor: '#ca8a04',
        border: "2px solid #eab308",
        opacity: "0.85",
    },
    '.alert-blue' : {
        padding: "1em",
        borderRadius: "10px",
        backgroundColor: '#1e40af',
        border: "2px solid #1d4ed8",
        opacity: "0.85",
    },
    '.alert-purple' : {
        padding: "1em",
        borderRadius: "10px",
        backgroundColor: '#7e22ce',
        border: "2px solid #9333ea",
        opacity: "0.85",
    },
    '.alert-gray' : {
        padding: "1em",
        borderRadius: "10px",
        backgroundColor: '#404040',
        border: "2px solid #525252",
        opacity: "0.85",
    },
    '.alert-light' : {
        padding: "1em",
        borderRadius: "10px",
        backgroundColor: '#d4d4d4',
        border: "2px solid #e5e5e5",
        opacity: "0.85",
        color:"black",
    },

    //Alert alternative
    '.alert-alternative-green' : {
        padding: "1em",
        borderRadius: "10px",
        border: "2px solid #257035",
        opacity: "0.85",
        color : "#2b8e41",
    },
    '.alert-alternative-red' : {
        padding: "1em",
        borderRadius: "10px",
        border: "2px solid #b22a2a",
        opacity: "0.85",
        color : "#cd3535",
    },
    '.alert-alternative-orange' : {
        padding: "1em",
        borderRadius: "10px",
        border: "2px solid #ea580c",
        opacity: "0.85",
        color : "#f97316",
    },
    '.alert-alternative-yellow' : {
        padding: "1em",
        borderRadius: "10px",
        border: "2px solid #ca8a04",
        opacity: "0.85",
        color : "#eab308",
    },
    '.alert-alternative-blue' : {
        padding: "1em",
        borderRadius: "10px",
        border: "2px solid #1e40af",
        opacity: "0.85",
        color : "#1d4ed8",
    },
    '.alert-alternative-purple' : {
        padding: "1em",
        borderRadius: "10px",
        border: "2px solid #7e22ce",
        opacity: "0.85",
        color : "#9333ea",
    },
    '.alert-alternative-gray' : {
        padding: "1em",
        borderRadius: "10px",
        border: "2px solid #404040",
        opacity: "0.85",
        color : "#525252",
    },
    '.alert-alternative-light' : {
        padding: "1em",
        borderRadius: "10px",
        border: "2px solid #d4d4d4",
        opacity: "0.85",
        color:"black",
        color : "#e5e5e5",
    },
}