export default {
  ".btn-green": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #257035",
    backgroundColor: "#2b8e41",
    color: "white",
  },
  ".btn-red": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #b22a2a",
    backgroundColor: "#cd3535",
    color: "white",
  },
  ".btn-orange": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #ea580c",
    backgroundColor: "#f97316",
    color: "white",
  },
  ".btn-yellow": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #ca8a04",
    backgroundColor: "#eab308",
    color: "white",
  },
  ".btn-blue": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #1e40af",
    backgroundColor: "#1d4ed8",
    color: "white",
  },
  ".btn-purple": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #7e22ce",
    backgroundColor: "#9333ea",
    color: "white",
  },
  ".btn-gray": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #404040",
    backgroundColor: "#525252",
    color: "white",
  },
  ".btn-light": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #d4d4d4",
    backgroundColor: "#e5e5e5",
    color: "black",
  },

  //Button with hover
  ".btn-green-h": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid transparent",
    backgroundColor: "#2b8e41",
    color: "white",
  },
  ".btn-green-h:hover": {
    borderColor: "#257035",
  },
  ".btn-red-h": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid transparent",
    backgroundColor: "#cd3535",
    color: "white",
  },
  ".btn-red-h:hover": {
    borderColor: "#b22a2a",
  },
  ".btn-orange-h": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid transparent",
    backgroundColor: "#f97316",
    color: "white",
  },
  ".btn-orange-h:hover": {
    borderColor: "#ea580c",
  },
  ".btn-yellow-h": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid transparent",
    backgroundColor: "#eab308",
    color: "white",
  },
  ".btn-yellow-h:hover": {
    borderColor: "#ca8a04",
  },
  ".btn-blue-h": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid transparent",
    backgroundColor: "#1d4ed8",
    color: "white",
  },
  ".btn-blue-h:hover": {
    borderColor: "#1e40af",
  },
  ".btn-purple-h": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid transparent",
    backgroundColor: "#9333ea",
    color: "white",
  },
  ".btn-purple-h:hover": {
    borderColor: "#7e22ce",
  },
  ".btn-gray-h": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid transparent",
    backgroundColor: "#525252",
    color: "white",
  },
  ".btn-gray-h:hover": {
    borderColor: "#404040",
  },
  ".btn-light-h": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid transparent",
    backgroundColor: "#e5e5e5",
    color: "black",
  },
  ".btn-light-h:hover": {
    borderColor: "#d4d4d4",
  },

  //Button outline
  ".btn-outline-green": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #257035",
    color: "#2b8e41",
  },
  ".btn-outline-green:hover": {
    backgroundColor: "#2b8e41",
    color: "white",
  },
  ".btn-outline-red": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #b22a2a",
    color: "#cd3535",
  },
  ".btn-outline-red:hover": {
    backgroundColor: "#cd3535",
    color: "white",
  },
  ".btn-outline-orange": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #f97316",
    color: "#f97316",
  },
  ".btn-outline-orange:hover": {
    backgroundColor: "#f97316",
    color: "white",
  },
  ".btn-outline-yellow": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #eab308",
    color: "#eab308",
  },
  ".btn-outline-yellow:hover": {
    backgroundColor: "#eab308",
    color: "white",
  },
  ".btn-outline-blue": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #1d4ed8",
    color: "#1d4ed8",
  },
  ".btn-outline-blue:hover": {
    backgroundColor: "#1d4ed8",
    color: "white",
  },
  ".btn-outline-purple": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #9333ea",
    color: "#9333ea",
  },
  ".btn-outline-purple:hover": {
    backgroundColor: "#9333ea",
    color: "white",
  },
  ".btn-outline-gray": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #525252",
    color: "#525252",
  },
  ".btn-outline-gray:hover": {
    backgroundColor: "#525252",
    color: "white",
  },
  ".btn-outline-light": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #e5e5e5",
    color: "#e5e5e5",
  },
  ".btn-outline-light:hover": {
    backgroundColor: "#e5e5e5",
    color:"black"
  },

  //Disabled Button
  "button:disabled:hover,button[disabled]": {
    opacity: "75%",
    border: "2px solid",
    color: "#0f172a",
  },
  ".btn-outline-green:disabled": {
    backgroundColor: "#2b8e41",
  },
  ".btn-outline-red:disabled": {
    backgroundColor: "#cd3535",
  },
  ".btn-outline-orange:disabled": {
    backgroundColor: "#f97316",
  },
  ".btn-outline-yellow:disabled": {
    backgroundColor: "#eab308",
  },
  ".btn-outline-blue:disabled": {
    backgroundColor: "#1d4ed8",
  },
  ".btn-outline-purple:disabled": {
    backgroundColor: "#9333ea",
  },
  ".btn-outline-gray:disabled": {
    backgroundColor: "#525252",
  },
  ".btn-outline-light:disabled": {
    backgroundColor: "#e5e5e5",
  },

  //Normal button focus
  ".btn-focus-green": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #257035",
    backgroundColor: "#2b8e41",
    color: "white",
  },
  ".btn-focus-green:focus" : {
    outline: "none",
    boxShadow: "0 0 0 2px rgba(43, 142, 65, 0.5)",
  },
  ".btn-focus-red": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #b22a2a",
    backgroundColor: "#cd3535",
    color: "white",
  },
  ".btn-focus-red:focus" : {
    outline: "none",
    boxShadow: "0 0 0 2px rgba(178, 42, 42, 0.5)",
  },
  ".btn-focus-orange": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #ea580c",
    backgroundColor: "#f97316",
    color: "white",
  },
  ".btn-focus-orange:focus" : {
    outline: "none",
    boxShadow: "0 0 0 2px rgba(234, 88, 12, 0.5)",
  },
  ".btn-focus-yellow": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #ca8a04",
    backgroundColor: "#eab308",
    color: "white",
  },
  ".btn-focus-yellow:focus" : {
    outline: "none",
    boxShadow: "0 0 0 2px rgba(202, 138, 4, 0.5)",
  },
  ".btn-focus-blue": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #1e40af",
    backgroundColor: "#1d4ed8",
    color: "white",
  },
  ".btn-focus-blue:focus" : {
    outline: "none",
    boxShadow: "0 0 0 2px rgba(30, 64, 175, 0.5)",
  },
  ".btn-focus-purple": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #7e22ce",
    backgroundColor: "#9333ea",
    color: "white",
  },
  ".btn-focus-purple:focus" : {
    outline: "none",
    boxShadow: "0 0 0 2px rgba(126, 34, 206, 0.5)",
  },
  ".btn-focus-gray": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #404040",
    backgroundColor: "#525252",
    color: "white",
  },
  ".btn-focus-gray:focus" : {
    outline: "none",
    boxShadow: "0 0 0 2px rgba(64, 64, 64, 0.5)",
  },
  ".btn-focus-light": {
    paddingLeft: "1.5rem",
    paddingRight: "1.5rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    borderRadius: "999px",
    border: "2px solid #d4d4d4",
    backgroundColor: "#e5e5e5",
    color: "black",
  },
  ".btn-focus-light:focus" : {
    outline: "none",
    boxShadow: "0 0 0 2px rgba(212, 212, 212, 0.5)",
  },
};
